language: android

android:
  components:
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

jdk:
  - oraclejdk8
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script: "./gradlew assembleDebug;./gradlew testDebug"


after_success:
- ./gradlew jacocoTestReport coveralls

notifications:
  email: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle